services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    shm_size: 128mb
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data

  web:
    build: .
    image: web:latest
    container_name: web
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/usr/src/app/.static

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static:/www/static

volumes:
  db:
  static:
